kind: pipeline
type: docker
name: evaluation-frontend

volumes:
  - name: node_modules
    host:
      path: /root/.cache/drone/node_modules
  - name: docker-cert-persistence
    temp: { }
  - name: ssh-key
    host:
      path: /root/.ssh/id_rsa

steps:
  - name: Adding SSL Certificate
    image: mirror.baidubce.com/library/busybox:1
    volumes:
      - name: docker-cert-persistence
        path: /etc/docker/certs.d/
    commands:
      - mkdir -p /etc/docker/certs.d/172.22.121.50
      - cp /registry_cert.crt /etc/docker/certs.d/172.22.121.50/ca.crt
  - name: install dependencies
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    image: mirror.baidubce.com/library/node:18.6.0-alpine
    commands:
      - mkdir -p ./node_modules
      - export NODE_MODULES_PATH=`pwd`/node_modules
      - npm install --registry=https://registry.npmmirror.com/
  - name: Test and lint
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    image: mirror.baidubce.com/library/node:18.6.0-alpine
    commands:
      - npm run format
      - npm run lint
  - name: Build dist
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    image: mirror.baidubce.com/library/node:18.6.0-alpine
    commands:
      - npm run build
  - name: Build image
    image: mirror.baidubce.com/plugins/docker:linux-amd64
    volumes:
      - name: docker-cert-persistence
        path: /etc/docker/certs.d/
    settings:
      registry: https://172.22.121.50
      repo: 172.22.121.50/ai-evaluation/evaluation-frontend
      insecure: true
      username:
        from_secret: docker_name
      password:
        from_secret: docker_password
      tags: ${DRONE_BUILD_NUMBER}
  - name: deploy
    image: mirror.baidubce.com/appleboy/drone-ssh
    volumes:
      - name: ssh-key
        path: /root/ssh/drone_rsa
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      port: 22
      key_path: /root/ssh/drone_rsa
      script:
        - echo "=======start deploy======="
        - docker stop evaluation-frontend
        - docker rm evaluation-frontend
        - docker run -di -p 80:80 --name evaluation-frontend 172.22.121.50/ai-evaluation/evaluation-frontend:${DRONE_BUILD_NUMBER}
        - docker rmi $(docker images | grep 172.22.121.50/ai-evaluation/evaluation-frontend | awk '{print $3}')
        - echo "=======deploy success======="
  - name: notify
    image: mirror.baidubce.com/drillster/drone-email:latest
    settings:
      host: smtp.qq.com
      port: 465
      username:
        from_secret: smtp_username
      password:
        from_secret: smtp_password
      from:
        from_secret: smtp_username
    when:
      status:
        - success
        - changed
        - failure